// Auto-generated by scripts/build.js. Do not edit manually.
// One check per colour in DesignTokens.Palette (21), tokens.json v1.21.0.

import SwiftUI
import XCTest
@testable import IAMJARLDesignTokens

final class PaletteTests: XCTestCase {
  func testEveryPaletteColourResolvesPerAppearance() throws {
    try assertAdaptive(DesignTokens.Palette.primary, light: DesignTokens.ColorToken.Light.primary, dark: DesignTokens.ColorToken.Dark.primary, "primary")
    try assertAdaptive(DesignTokens.Palette.onPrimary, light: DesignTokens.ColorToken.Light.onPrimary, dark: DesignTokens.ColorToken.Dark.onPrimary, "onPrimary")
    try assertAdaptive(DesignTokens.Palette.primaryHover, light: DesignTokens.ColorToken.Light.primaryHover, dark: DesignTokens.ColorToken.Dark.primaryHover, "primaryHover")
    try assertAdaptive(DesignTokens.Palette.primaryPressed, light: DesignTokens.ColorToken.Light.primaryPressed, dark: DesignTokens.ColorToken.Dark.primaryPressed, "primaryPressed")
    try assertAdaptive(DesignTokens.Palette.primarySubtle, light: DesignTokens.ColorToken.Light.primarySubtle, dark: DesignTokens.ColorToken.Dark.primarySubtle, "primarySubtle")
    try assertAdaptive(DesignTokens.Palette.Text.primary, light: DesignTokens.ColorToken.Light.Text.primary, dark: DesignTokens.ColorToken.Dark.Text.primary, "text.primary")
    try assertAdaptive(DesignTokens.Palette.Text.secondary, light: DesignTokens.ColorToken.Light.Text.secondary, dark: DesignTokens.ColorToken.Dark.Text.secondary, "text.secondary")
    try assertAdaptive(DesignTokens.Palette.Text.tertiary, light: DesignTokens.ColorToken.Light.Text.tertiary, dark: DesignTokens.ColorToken.Dark.Text.tertiary, "text.tertiary")
    try assertAdaptive(DesignTokens.Palette.Text.disabled, light: DesignTokens.ColorToken.Light.Text.disabled, dark: DesignTokens.ColorToken.Dark.Text.disabled, "text.disabled")
    try assertAdaptive(DesignTokens.Palette.Text.inverse, light: DesignTokens.ColorToken.Light.Text.inverse, dark: DesignTokens.ColorToken.Dark.Text.inverse, "text.inverse")
    try assertAdaptive(DesignTokens.Palette.Background.app, light: DesignTokens.ColorToken.Light.Background.app, dark: DesignTokens.ColorToken.Dark.Background.app, "background.app")
    try assertAdaptive(DesignTokens.Palette.Background.muted, light: DesignTokens.ColorToken.Light.Background.muted, dark: DesignTokens.ColorToken.Dark.Background.muted, "background.muted")
    try assertAdaptive(DesignTokens.Palette.Background.card, light: DesignTokens.ColorToken.Light.Background.card, dark: DesignTokens.ColorToken.Dark.Background.card, "background.card")
    try assertAdaptive(DesignTokens.Palette.Background.disabled, light: DesignTokens.ColorToken.Light.Background.disabled, dark: DesignTokens.ColorToken.Dark.Background.disabled, "background.disabled")
    try assertAdaptive(DesignTokens.Palette.Surface.`default`, light: DesignTokens.ColorToken.Light.Surface.`default`, dark: DesignTokens.ColorToken.Dark.Surface.`default`, "surface.default")
    try assertAdaptive(DesignTokens.Palette.Surface.raised, light: DesignTokens.ColorToken.Light.Surface.raised, dark: DesignTokens.ColorToken.Dark.Surface.raised, "surface.raised")
    try assertAdaptive(DesignTokens.Palette.Border.subtle, light: DesignTokens.ColorToken.Light.Border.subtle, dark: DesignTokens.ColorToken.Dark.Border.subtle, "border.subtle")
    try assertAdaptive(DesignTokens.Palette.Border.`default`, light: DesignTokens.ColorToken.Light.Border.`default`, dark: DesignTokens.ColorToken.Dark.Border.`default`, "border.default")
    try assertAdaptive(DesignTokens.Palette.State.success, light: DesignTokens.ColorToken.Light.State.success, dark: DesignTokens.ColorToken.Dark.State.success, "state.success")
    try assertAdaptive(DesignTokens.Palette.State.warning, light: DesignTokens.ColorToken.Light.State.warning, dark: DesignTokens.ColorToken.Dark.State.warning, "state.warning")
    try assertAdaptive(DesignTokens.Palette.State.error, light: DesignTokens.ColorToken.Light.State.error, dark: DesignTokens.ColorToken.Dark.State.error, "state.error")
  }
}
